on:
  workflow_call:
    inputs:
      region:
        type: string
        required: false
      repository_name:
        type: string
        required: false
      gcp_project_id:
        type: string
        required: false
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@v0
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
      - name: Container Build
        uses: martoc/action-container-build@v0
        with:
          registry: gcp
          region: ${{ inputs.region }}
          repository_name: ${{ inputs.repository_name }}
          gcp_project_id: ${{ inputs.gcp_project_id }}
      - name: Release on GitHub
        uses: martoc/action-release@v0
        if: ${{ github.event_name != 'pull_request' }}
