---
name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
          fetch-tags: true
      - name: Check out action-tag repository
        uses: actions/checkout@v4
        with:
          repository: martoc/action-tag
          ref: main
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          path: ./.github/actions/action-tag
      - name: Tag
        uses: ./.github/actions/action-tag
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Check out action-release repository
        uses: actions/checkout@v4
        with:
          repository: martoc/action-release
          ref: main
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          path: ./.github/actions/action-release
      - name: Release on GitHub
        uses: ./.github/actions/action-release
